### ISSUE TITLE
python 3.5/3.6?

### ISSUE THREAD

**Issue by bcail** [cyface/django-termsandconditions#121]
First, thanks for this package.

Python 3.5/3.6 are still supported (in security mode): https://devguide.python.org/#status-of-python-branches. Django 2.2 also supports Python 3.5 and 3.6: https://docs.djangoproject.com/en/2.2/releases/2.2/#python-compatibility. Would you be open to a PR that re-adds support for them to this package (or at least for Python 3.6)?

**Comment by cyface** [comment]
@bcail Yes!

**Comment by cyface** [comment]
Thanks for the PR! Release is on the way out!

**Comment by bcail** [comment]
@cyface Thanks. I don't see the new release on pypi yet - is that still in process?

**Comment by cyface** [comment]
@bcail Up now! https://pypi.org/project/django-termsandconditions/

**Comment by bcail** [comment]
thanks.
