### ISSUE TITLE
NoReverseMatch at /terms/

### ISSUE THREAD

**Issue by 9mido** [cyface/django-termsandconditions#126]
NoReverseMatch at /terms/

Reverse for 'tc_print_page' with arguments '('', '')' not found. 1 pattern(s) tried: ['terms/print/(?P<slug>[a-zA-Z0-9_.-]+)/(?P<version>[0-9.]+)/$']

"GET /terms/ HTTP/1.1" 500 178082

Requested Terms and Conditions that Have Not Been Created.
Internal Server Error: /terms/

After navigating to 127.0.0.1:8000/terms/ I received the error above.

All of these other URLs work however after adding data to the terms and conditions models inside 127.0.0.1:8000/admin/:
/terms/print/terms_slug/1.0/
/terms/view/terms_slug/1.0/
/terms/email/
/terms/accept/

I am using Django 3.0.3, Python 3.7.3, and the latest version of django-termsandconditions 2.0.2. 

In version 2.0 of django-termsandconditions in combination with Django 2.2.9 and Sqlite (not sure exactly if the Django version / database is to blame or the newly added django-termsandconditions project update for the error above), I was able to navigate to /terms/ without a problem as well as the other URL endings above. 

In addition to this error, I want to point out that the build for this project says build error and "some check were not successful" and pyup has 4 updates as well. Maybe this problem is related to this? Otherwise please fix these as well as it makes people hesitant to install this project since github is displaying this to users. 

I would also like for this project to work on the latest Django 3 and Python 3 and be Postgres 12 compatible. This error might be showing up because of my recent move to Postgres 12 and upgrade to Django 3.0.3 or because the this project was updated a few days ago. Not sure.

**Comment by cyface** [comment]
Thank you for the report! I will take a look.

**Comment by cyface** [comment]
@9mido I'll keep looking, but basically, this is the error that you get if no terms exist. If you create the default site-terms 1.0 in the admin and make it active, this error should go away.

**Comment by 9mido** [comment]
@cyface Thanks for the quick response. I did not use the default name 'site-terms' at first and used a different custom slug name which caused the error. But when I just used your suggestion of the default 'site-terms' the error did indeed go away. I guess there is no way for anybody to use a custom slug for the terms? Thank you very much for your efforts. I am glad that I was able to help you find this so that you could further improve this great project.

**Comment by cyface** [comment]
@9mido Thanks! I've added a new release that better handles both no terms defined, as well as allowing alternative slugs for the base terms. I hope this helps! Cheers!
