### ISSUE TITLE
TERMS_EXCLUDE_URL_LIST Regular Expressions For Custom Slug Name

### ISSUE THREAD

**Issue by 9mido** [cyface/django-termsandconditions#129]
Now that the user could use any custom slug name, there needs to be a way to define that new custom slug name in settings so that every time a user changes the slug in admin, settings will be updated automatically.

For example, instead of:
TERMS_EXCLUDE_URL_LIST = {'/terms/accept/site-policy/'}

Do something like (using regular expressions):
TERMS_EXCLUDE_URL_LIST = {'\/terms\/accept\/.*\/'}

Not sure if this is currently possible using the current code or not. Please let me know.

The reason I want to do this is because I am running this project twice in my Django project. Once is for my site's terms and conditions and the other time is for my site's privacy policy. I would love if this project had an exact github package copy but for privacy policy. Where any code change in the terms and conditions github would need to be changed in the privacy policy github and vice versa. If not, no big deal I will just have to copy this terms and conditions project and change the variables to privacy policy ones myself and add to my django project as an app every time there is an update to the code. 

Note for other users who want to run this project twice: in the TERMS_EXCLUDE_URL_LIST and POLICY_EXCLUDE_URL_LIST (this I made from changing the variables) there needs to be an exclusion of every policy URL in the TERMS_EXCLUDE_URL_LIST like this: TERMS_EXCLUDE_URL_LIST = {'/policyrequired/', '/policy/', '/policy/accept/', '/policy/accept/site-policy/'} in order to run both projects at the same time.

**Comment by cyface** [comment]
@9mido Yes, there is only the ability to exclude URLs from being prompted for terms at all or not - there's currently no way to have a different set of excludes per term.
