### ISSUE TITLE
Version 2.0.3 Unable To View Content At /terms/ After Accepting

### ISSUE THREAD

**Issue by 9mido** [cyface/django-termsandconditions#133]
In 2.0.3 when I login and then accept the terms, I am unable to view any HTML content for the terms that this github project normally produces from the database entries. It just shows a blank page at /terms/ after accepting. When rolling back to 2.0.2, it works again and I am able to view the HTML content at /terms/ again after accepting. 

If needed, perhaps rolling back this project back to 2.0.2 would be best. Regarding my previous issue, now I know that it is necessary to not re-name the slug to anything else other than site-terms so I do not mind reverting back to 2.0.2. The maintainer team of this project needs to decide moving forward whether they want to prevent accidental / custom changes to the slug in admin or in settings. Maybe make it a disabled field in admin. It would have been nice though to make your own custom slug but if not, so be it. If reverting back to 2.0.2, I highly recommend updating the documentation with a warning saying "Do not change the slug to anything other than site-terms".

**Comment by cyface** [comment]
@9mido New release is out. I believe the issue was because of caching and AnonymousUsers.  Let me know if the 2.0.4 helps you out. Cheers.

**Comment by 9mido** [comment]
@cyface I just tried 2.0.4 and I am still having this same problem as issue #133. My /terms/ page is blank after accepting. Using /terms/print/site-terms/1.0/ as the link on my website <a> tag is complicated because the version and the slug name could change over time. Being able to use /terms/ works better for me because anybody could view the terms and conditions after accepting no matter what you change the version and slug name to.

**Comment by cyface** [comment]
*after* accepting? That page hides all already-accepted terms, so it should
say “no terms”.

If you want a page that just lists all terms regardless of whether they
have been accepted or not, you can use the
TermsAndConditions.get_active_terms()method in a custom TemplateView’s
get_context() method and list them out.

**Comment by 9mido** [comment]
@cyface Here hopefully this makes it easier to see what is happening:

https://streamable.com/wz30z

Ok that is good to know I may try that.

**Comment by 9mido** [comment]
@cyface I just tried your latest commits. 

https://streamable.com/xcclm

So /terms/ works without accepting but after accepting it does. Should the URL on my site only be /terms/active/ at all times?

**Comment by cyface** [comment]
Right, I added that URL for your use case. The /terms/ url only shows
unaccepted, /terms/active/ shows all active regardless of acceptance.

**Comment by 9mido** [comment]
@cyface okay gotcha.

I just discovered a new problem though. When I change the version of the old terms and conditions to a newer one, the user is not able to accept the new terms. It automatically says in admin that they accepted the new terms without their consent? 

https://streamable.com/6pe0g

**Comment by cyface** [comment]
You can’t change the version of existing terms. You need to make a new
terms object with a new version number. That way the old terms live on
forever.

**Comment by 9mido** [comment]
@cyface okay thanks for letting me know. 

Yes you are correct. However, when I make a new terms with a different slug name, it will show both terms and conditions on the /terms/active/ page. Shouldn't it only show one based on the most recent date maybe? 

https://streamable.com/ofsx8

Also just for a reference here is what I was talking about with 2.0.2 where /terms/ worked no matter what. I am not sure what changed from that version that you had to make /terms/active/ ? That is what I am confused about? But you see what I mean?

https://streamable.com/1l40m

**Comment by cyface** [comment]
If you have terms with a slug of my-terms, you clone it each time you
update it, and keep the same slug, but with a new version number. It
auto-selects the latest terms for any given slug based on the date and
version number.

**Comment by 9mido** [comment]
@cyface right that I understand. I just want to help make it more bulletproof for employees who might not know that information and just change things randomly. 2.0.2 just worked for those use cases so well. Sorry for making you do this extra work but maybe I should not have opened my mouth the first time :/

https://streamable.com/3vuml

**Comment by cyface** [comment]
Historically,  /terms/ was only supposed to list terms that hadn’t yet been
accepted, so everyone who was using it that way had it break in Django 2,
as it started showing all terms. So I fixed that bug, so now it’s back to
the way it has always worked previously, where /terms/ only shows terms not
yet accepted.

So I added a new view for you so list all terms regardless of whether they
had been accepted.

It’s a core feature to allow multiple active terms with different slugs,
but only one active version per slug.

**Comment by 9mido** [comment]
@cyface ah ok I am rather new when it comes to using this package so I did not know about that. Ok thanks for the clarification. So showing more than one slug like in this video https://streamable.com/ofsx8 in the new version you just updated is normal to show people all the terms that historically changed?
