### ISSUE TITLE
Template tags to determine if user accepted terms or not

### ISSUE THREAD

**Issue by 9mido** [cyface/django-termsandconditions#134]
@cyface 

Is there a template tag to determine if the user accepted or declined the terms and conditions? I want to do something like:

```
If user accepts:
<a href="/terms/active/">
​
Else:
<a href="/terms/">
​
Print Link With Template Tags:
<a href="/terms/print/{{slug}}/{{version}}/">
```
I am not sure what the condition of the if statement template tag would be to determine if the user accepted/declined the terms or not. Or if there is a template tag to determine active or not?

Also, what order / hierarchy would you recommend for an if statement like this? 

Feel free to close this issue and reply with a comment I will search for it later on.

**Comment by 9mido** [comment]
```
{% for terms in request.user.userterms.all %}
{% if request.user.is_anonymous %}
<a href="/terms/print/{% for terms in terms_list %}{{ terms.slug|safe }}/{{ terms.version_number|safe }}{% endfor %}/">Terms and Conditions</a>
{% elif terms.user|safe %}
<a href="/terms/active/">Terms and Conditions</a>
{% else  %}
<a href="/terms/{% for terms in terms_list %}{{ terms.slug|safe }}{% endfor %}">Terms and Conditions</a>
{% endif %}
{% endfor %}
```

**Comment by 9mido** [comment]
@cyface 

Sorry I want to reopen this issue (not sure how. I thought I had it figured out but the logic I have above only works for

**Comment by cyface** [comment]
Is this just for a link in the footer to let people view the current site terms?

**Comment by 9mido** [comment]
@cyface yes.

**Comment by cyface** [comment]
I guess I am not getting what you are trying to do.  Typically, folks are just pointing to "Site Terms" -> /terms/site-terms/ to always show the latest site terms, and /terms/privacy-policy/ to always link to the latest privacy policy, etc.  I set up /terms/active/ to list and show all active terms.  I'm not clear why you need to check to see if they have accepted terms just to link in the footer to a page where they can see the all the terms.  At this point, you are so far outside the use case of this project, that I am not sure I can further assist.

**Comment by 9mido** [comment]
@cyface ah okay that makes sense, I did not know about that. In the past couple of days, I was more confused than anything regarding how things worked. Thank you for clearing things up for me and making such quick improvements to this project.
