### ISSUE TITLE
Add rel="noopener noreferrer" to target="_blank"

### ISSUE THREAD

**Issue by 9mido** [cyface/django-termsandconditions#136]
Noticed that on some of the templates with target="_blank" it is vulnerable to reverse tabnapping since it is missing rel="noopener noreferrer".

https://stackoverflow.com/questions/50709625/link-with-target-blank-and-rel-noopener-noreferrer-still-vulnerable/50709760

https://developers.google.com/web/tools/lighthouse/audits/noopener

However, this may not be a concern if users choose to override the templates.

**Comment by cyface** [comment]
Added!
