### ISSUE TITLE
/terms/email/ and /terms/email/site-terms/version_number/ not working

### ISSUE THREAD

**Issue by 9mido** [cyface/django-termsandconditions#147]
The email form in /terms/email/ and /terms/email/site-terms/version_number/ is not working. 

I actually do not need this feature at all and maybe including a setting to disable these links / form is a good idea?

I suppose if they do not work that is fine as long as it cannot be compromised by a hacker  / spam bots.

**Comment by cyface** [comment]
You can add a config to your project's urls.py to redirect those to
somewhere else if you want to be extra safe that no one can submit to them.

**Comment by 9mido** [comment]
I was able to do this:

from django.views.defaults import page_not_found
url('^terms/email/', page_not_found, {'exception': Exception()}),

Thanks for the tip also which allowed me to get there
