### ISSUE TITLE
How to best optimize URLs for SEO?

### ISSUE THREAD

**Issue by 9mido** [cyface/django-termsandconditions#148]
I guess this is a general question but this package has a lot of links and some of them have duplicate content. 

Which links should be included in sitemap.xml and disallowed in robots.txt?

Some of the URLs can be accessed when the user is logged out and logged in. For instance, /terms/accept/, /terms/accept/site-terms/, /terms/accept/site-terms/version_number/ can all be accessed when logged out which doesn't make sense logically but I guess it is fine and doesn't need a code change as long as pressing accept does not do anything when logged out and logged in (only after previously accepting another time). 

Google bot will probably see these links so I guess this would be a good way to do it?

sitemap.xml:
```
<url>
<loc>http://example.com/terms/view/site-terms/</loc>
<changefreq>always</changefreq>
<priority>0.9</priority>
</url>

```
Robot.txt:

Disallow:
/terms/
/terms/active/
/terms/accept/
/terms/accept/site-terms/
/terms/accept/site-terms/version_number/
/terms/view/site-terms/version_number/
/terms/email/
/terms/email/site-terms/version_number/
/terms/print/site-terms/version_number/

Off topic rant: If you were to make some of those views @login_required, it may have a conflict with django-allauth and django-two-factor-auth I discovered in some of my other issue reports if those packages are used together where a logged out user could access django-two-factor-auth admin login page from a valid login only view URL. (so i don't mind if you don't change the code because of this)

**Comment by cyface** [comment]
Thanks seems like a reasonable approach!

**Comment by 9mido** [comment]
Ok awesome just wanted to make sure.
