### ISSUE TITLE
Spam Protection Question

### ISSUE THREAD

**Issue by 9mido** [cyface/django-termsandconditions#154]
This is kind of a dumb question. But would like to hear your thoughts. Feel free to close this issue if the answer is no. 

https://github.com/cyface/django-termsandconditions/blob/master/termsandconditions/templates/termsandconditions/tc_accept_terms.html

Does the form on this page need a captcha / honeypot field to stop spam? The only thing a user / bot could really do is click accept to the terms and conditions and they can't really do anything else. But since it is a form I am not sure.

**Comment by cyface** [comment]
Hi! - I can't think of any reason - not much nefarious you can do by accepting terms.
