### ISSUE TITLE
Multi terms: TOS and Privacy policy

### ISSUE THREAD

**Issue by aktywnitu** [cyface/django-termsandconditions#16]
It is possible by slug, but decorator check only DEFAULT_TERMS_SLUG:

```
TermsAndConditions.agreed_to_latest(request.user)
```
```
def agreed_to_latest(user, slug=DEFAULT_TERMS_SLUG):
```

**Comment by cyface** [comment]
Hi there -

 That method declaration is setting slug to the default value only if no value is passed in for the slug.

 Here's a place in the tests where non-default values are being passed in: https://github.com/cyface/django-termsandconditions/blob/master/termsandconditions/tests.py#L87
