### ISSUE TITLE
Feature request - Terms Checkbox On Signup Page For Consent & Middleware Setting

### ISSUE THREAD

**Issue by 9mido** [cyface/django-termsandconditions#161]
@cyface 

This is a feature request. Be able to ask the user for their terms and conditions consent on the signup page via a checkbox that should submit to the terms and conditions database logs but then do not run the middleware after a successful signup for the first time. Then for new updates to the terms, the middleware could run normally. 

Maybe have a setting like TERMS_MIDDLEWARE_ACTIVE_ON_SIGNUP = True|False would do the trick. 

It occurred to me that doing something like asking for the user's PII like their email address on the signup page might be a violation of laws without their consent directly on that signup page. Since the current behavior with the middleware only allows a user to consent to the terms right after signing up and not during the signup page itself when it is already to late to consent about their PII being collected. 

Here is my code below. Wondering how to get the checkbox to be able to log to the terms and conditions models instead of my own model especially without the user being created yet. I am using django-allauth's signup form. Or maybe I should just keep their response to the terms checkbox in my own model and not in the terms and conditions model?

Forms.py: 
```
class CustomCheckbox(Field):
    template = 'custom_checkbox.html'

class SignupForm(SignupForm):
	terms_consent = forms.BooleanField(required=True,initial=False,label='I consent to the terms and conditions?')
	field_order = ['username', 'email', 'password1', 'password2', 'terms_consent',]
	def __init__(self, *args, **kwargs):
    	super(SignupForm, self).__init__(*args, **kwargs)
    	self.fields['terms_consent'].widget.attrs['class'] = ''
    	self.fields['terms_consent'].widget.attrs['type'] = 'checkbox'
    	self.helper = FormHelper()
    	self.helper.layout = Layout(
        	CustomCheckbox('is_age_compliant'),
    	)
	pass

	def save(self, request):
    	user = super().save(request)
    	profile = Profile(user=user,terms_consent=True)
    	user.save()
    	profile.save()
    	return user

	class Meta:
    	model = Profile
    	fields = ('terms_consent')

```

Signup.html:

```
<form class="signup" id="signup_form" autocomplete="off" method="post" action="{% url 'account_signup' %}">
  {% csrf_token %}
  {{ form.username|as_crispy_field }}
  {{ form.email|as_crispy_field }}
  {{ form.password1|as_crispy_field }}
  {{ form.password2|as_crispy_field }}
  {{ form.terms_consent|as_crispy_field }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <button type="submit" class="btn btn-primary form-control">{% trans "Sign Up" %} &raquo;</button>
</form>
```

Custom Checkbox.html:

```
{% load crispy_forms_field %}

<div class="form-group">
  <div class="custom-control custom-checkbox">
    {% crispy_field field 'class' 'custom-control-input' %}
    <label class="custom-control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
  </div>
</div>
```
Settings.py:
```
ACCOUNT_FORMS = {
    'signup': 'app.forms.SignupForm',
}
```
Models.py:

```
class Profile(models.Model):
	user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
	terms_consent = models.BooleanField(default=False, blank=True, null=True,)

	def __str__(self):
    	return self.user.username
```

**Comment by cyface** [comment]
Hello!  If I am understanding correctly, you should just be able do this in the save method of your SignupForm, after you create the user.  You can create a UserTermsAndConditions object (see https://github.com/cyface/django-termsandconditions/blob/master/termsandconditions/models.py#L22 ) with the User and Terms you had them agree to, and it will no longer prompt them to agree to those.  You'd need to look up the Terms object with the checkbox terms, or pass in it's id.

Something along the lines of:
```
user.save()
terms = TermsAndConditions.objects.get(slug='my-checkbox-terms')
UserTermsAndConditions.objects.create(terms=terms, user=user)
```

**Comment by 9mido** [comment]
@cyface if there is more than one slug such as 'site-terms' you get the following error -> get() returned more than one TermsAndConditions -- it returned 2!

Is there another query to use?

**Comment by cyface** [comment]
There is a helper method that would be good to use:

`TermsAndConditions.get_active(slug='site-terms')`

**Comment by 9mido** [comment]
Ok cool thanks!

Here is my code for anyone else who runs into this problem (just add to the code above):

Forms.py:

```
from termsandconditions.models import UserTermsAndConditions, TermsAndConditions

terms_checkbox = forms.BooleanField(required=True,initial=False,label='Accept terms?')
self.fields['terms_checkbox'].widget.attrs['class'] = ''
self.fields['terms_checkbox'].widget.attrs['type'] = 'checkbox'
self.helper = FormHelper()
self.helper.layout = Layout(CustomCheckbox('terms_checkbox'),)

user.save()
terms = TermsAndConditions.objects.filter(slug='site-terms').order_by('-date_active').first() #or use TermsAndConditions.get_active(slug='site-terms')
UserTermsAndConditions.objects.create(terms=terms, user=user)

```
Thank you!
