### ISSUE TITLE
Problems following the guideline for translations

### ISSUE THREAD

**Issue by goromachine** [cyface/django-termsandconditions#166]
I've checked the guideline on this package to make the translations and I don't know if I'm doing something wrong or maybe the guidelines are outdated (because they are from 2015). 

I could make the point 1 and point 2, but when trying to make the point `3. Add translation`, when running the `makemigrations` command I get the following message:

```
No changes detected in app 'termsandconditions'
```
I attach my code blocks related to this implementation:

settings.py
```
LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish')),
)

MIGRATION_MODULES = {
    # local path for migration for the termsandconditions
    'termsandconditions': 'ToS_translations.migrations.migrations_termsandconditions',
}
```

translation.py
```
from modeltranslation.translator import translator, TranslationOptions
from termsandconditions.models import TermsAndConditions


class TermsAndConditionsTranslationOptions(TranslationOptions):
    fields = ('name', 'text', 'info')


translator.register(TermsAndConditions, TermsAndConditionsTranslationOptions)

```

The structure of my project
```
-my_project
  - my_project
     - settings.py
     - ...
  - ToS_translations
     - migrations
         - migrations_termsandconditions
             - 001_initial.py
             - __init__.py
         - __init__.py
     - __init__.py
     - translation.py
  - other_apps
```

Thank you.

**Comment by cyface** [comment]
@goromachine Ah! You need to use this setting:

TERMS_EXCLUDE_URL_CONTAINS_LIST = (
    {}
)  # Useful if you are using internationalization and your URLs could change per language

And add /terms/ to that list, so that it excludes URLs that *contain* ``/terms/`` from the redirect.

I'll add that to the docs!

**Comment by goromachine** [comment]
That was it! 

In addition I will recommend add `` to the same list like this:

**Comment by cyface** [comment]
Great, I updated the README to that effect!
