### ISSUE TITLE
Avoid using inline javascript/css for content security policy

### ISSUE THREAD

**Issue by 9mido** [cyface/django-termsandconditions#173]
Some templates have inline javascript which is bad for content security policy. 

https://github.com/cyface/django-termsandconditions/blob/master/termsandconditions/templates/termsandconditions/snippets/termsandconditions.html

https://github.com/cyface/django-termsandconditions/blob/master/termsandconditions_demo/templates/404.html

https://github.com/cyface/django-termsandconditions/blob/master/termsandconditions_demo/templates/500.html

https://github.com/cyface/django-termsandconditions/blob/master/termsandconditions_demo/templates/error.html

I cannot find any other ones. Also check if there is inline css anywhere. There should not be any inline css/javascript code. 

You can use django-csp to test. 

On a side note, I also see some jquery links in the demo templates. Why not use vanilla javascript instead of jquery? Bootstrap v5 is moving away from jquery for speed and other reasons like not relying on another library. 

https://github.com/cyface/django-termsandconditions/blob/master/termsandconditions_demo/templates/base.html

**Comment by cyface** [comment]
Hey there! I can't remove inline .js and still have these modals be portable between applications.  If you need them to meet a particular security or .js approach, you can override the template in your app and make any adjustments you need. :)

**Comment by 9mido** [comment]
Fair enough. It was not a big deal anyways just wanted you to be aware and wanted to see what your opinion was.
