### ISSUE TITLE
Delete old user acceptances in the database when user accepts newer version

### ISSUE THREAD

**Issue by 9mido** [cyface/django-termsandconditions#175]
This is a feature request. To avoid filling up the database with additional user acceptances every time the terms get updated, why not delete the previous user acceptances and only keep the acceptances for that user regarding the latest version that they just accepted? Only delete the previous acceptances for that user if they accept the newest terms version. If they have not yet accepted the newest terms version, keep the old acceptance entry logged in the database still.

To satisfy all people who use django-termsandconditions, a setting like DELETE_OLD_ON_ACCEPT=True|False or whatever you want to call it would be needed for this to turn this on or off. Because maybe tracking all user acceptances in the database is needed no matter what the version of the terms is and maybe for legal purposes old acceptances would be needed to remain tracked in the database? 

Example:
User accepts version 1
User version 1 acceptance logged in the database
Terms updates to version 2
Same user accepts version 2
Same user acceptance from version 1 in the database gets deleted
Version 2 acceptance gets logged in the database for that user

**Comment by cyface** [comment]
Hmm, for legal reasons, I think most people will need to have all the history kept.  I think a good solution for you might be to write a quick management command that clears out the old accepts based on your criteria, and you could cron this to run quarterly/monthly/daily, or whatever suits your use case?

**Comment by 9mido** [comment]
@cyface True. 

I have the following queries:

```
from termsandconditions.models import TermsAndConditions, UserTermsAndConditions
from django.db.models import Count

UserTermsAndConditions.objects.values('user').annotate(Count('user')).order_by().filter(user__count__gt=1)
<QuerySet [{'user': 1, 'user__count': 2}]>

dupes = UserTermsAndConditions.objects.values('user').annotate(Count('user')).order_by().filter(user__count__gt=1)
UserTermsAndConditions.objects.filter(user__in=[item['user'] for item in dupes])
<QuerySet [<UserTermsAndConditions: admin:site-terms-2.00>, <UserTermsAndConditions: admin:site-terms-3.00>]>
```

I am stuck on how to delete all previous acceptances except the most recent one for that user. Any ideas?

**Comment by cyface** [comment]
Something like this might work for you:

```
class Command(BaseCommand):
    help = "Removes evidence of acceptance of previous versions of active terms."

    def handle(self, *args, **options):
        active_terms = TermsAndConditions.get_active_terms_list()
        for term in active_terms:
            old_accepts = UserTermsAndConditions.objects.filter(terms__slug=term.slug).exclude(terms__pk=term.pk)
            logger.debug(f"About to delete these old terms accepts: {old_accepts}")
            old_accepts.delete()
```

**Comment by 9mido** [comment]
Awesome, thank you!
