### ISSUE TITLE
Possiblity to integrate easily into forms

### ISSUE THREAD

**Issue by Kurt57** [cyface/django-termsandconditions#187]
Hi there,

is there a possibility to integrate easy into forms?

I mean that user accept the tac

**Comment by cyface** [comment]
Hello!

 There are forms used by the views that you can most likely use to include in your form:

https://github.com/cyface/django-termsandconditions/blob/7e528ada08b1bc7b3a4070f84025328e79565965/termsandconditions/forms.py#L11

The core functionality is to protect access to certain pages with terms and conditions, but there is no reason you couldn't use this method to get a list of all the active terms: https://github.com/cyface/django-termsandconditions/blob/7e528ada08b1bc7b3a4070f84025328e79565965/termsandconditions/models.py#L159

and then create a UserTermsAndConditions object as part of your form saving with the form id and the user id in it:
https://github.com/cyface/django-termsandconditions/blob/7e528ada08b1bc7b3a4070f84025328e79565965/termsandconditions/models.py#L22

Hope that helps!

**Comment by Kurt57** [comment]
very nice. thank you so much. 😊
