### ISSUE TITLE
Django (1.11 at least) creates migrations for termsandconditions

### ISSUE THREAD

**Issue by ciarancourtney** [cyface/django-termsandconditions#24]
The main difference I can see is the stripping of the bytestrings?

```
# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termsandconditions', '0002_termsandconditions_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='date_active',
            field=models.DateTimeField(blank=True, help_text='Leave Null To Never Make Active', null=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='info',
            field=models.TextField(blank=True, help_text="Provide users with some info about what's changed and why", null=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='slug',
            field=models.SlugField(default='site-terms'),
        ),
        migrations.AlterField(
            model_name='usertermsandconditions',
            name='date_accepted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Accepted'),
        ),
        migrations.AlterField(
            model_name='usertermsandconditions',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
    ]
```

On a separate note, would you be open to a PR which excludes Users from accepting terms if they have a certain permission?

**Comment by ciarancourtney** [comment]
I think the main issue is not having unicode_literals in models.py, see https://docs.djangoproject.com/en/1.11/topics/migrations/#supporting-python-2-and-3

I think you may have to generate a new migration using Python 3 in order to make app 2/3 compatible.

Working around this ATM by stripping the b's out of migration files after installation, as per last comment here https://code.djangoproject.com/ticket/23226

**Comment by cyface** [comment]
Thanks for the info, I'll take a look!

**Comment by ciarancourtney** [comment]
Thanks @cyface, also how about a setting to disable default term creation, is there any hard and fast reason this is in place ATM? It makes testing non-deterministic as a new object is created when the terms_required decorator is entered. Any workaround to disable this in short term?

**Comment by cyface** [comment]
I removed the auto terms creation and added the Python3 migration...new version is up on PyPi...

**Comment by ciarancourtney** [comment]
Brilliant, thanks @cyface

**Comment by ciarancourtney** [comment]
Hi @cyface I think the 1.1.13 release may have introduced a bug, if no terms are found a Http404 is raised, which it not caught by any of the calling functions. Why not just return None or an empty queryset?

**Comment by cyface** [comment]
@ciarancourtney I debated doing it both ways for 1.1.13 - I updated the code to return None instead in 1.1.14.
