### ISSUE TITLE
Add EXCLUDE_USERS_WITH_PERM setting

### ISSUE THREAD

**Issue by ciarancourtney** [cyface/django-termsandconditions#34]
Up until now I've wrapped terms_required to add this check.

@cyface I can submit PR if you'd approve this feature? Or can it already be accomplished?

**Comment by cyface** [comment]
Hi Ciaran -

 Is the idea to not show T&C’s if a user has a particular permission?

Thanks!


Tim

**Comment by ciarancourtney** [comment]
Yes exactly

**Comment by cyface** [comment]
I'm not aware of a way this can be done right now with terms_required, so
if you want to submit a PR including tests for it, please do!
