### ISSUE TITLE
Wysiwyg editor

### ISSUE THREAD

**Issue by LittleLampLight** [cyface/django-termsandconditions#36]
Hi! Great module so far. But it seems like some prettiness is missing. Can you include wysiwyg editor for T&C? Or i can create pull request i guess

**Comment by cyface** [comment]
Hi there - I've intentionally not included a WYSIWYG editor for T&C, since many people have their own preference as to which one to use and how they want to integrate it into their project, and that weight of whatever I included would be in addition to whatever they added.  Thanks!

**Comment by LittleLampLight** [comment]
Okay. Git it. Also i've seen, that there is no translate tags in templates for text like "Please Accept", "Print", "Accept" and etc. ? Can i add them?

**Comment by cyface** [comment]
Sure! Go for it! :)
