### ISSUE TITLE
TERMS_EXCLUDE_URL_LIST with i18n_patterns for url

### ISSUE THREAD

**Issue by LittleLampLight** [cyface/django-termsandconditions#39]
Seems like applications is not working correct with language code in [urls](https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#django.conf.urls.i18n.i18n_patterns). 

For example settings config to:

`TERMS_EXCLUDE_URL_LIST = ('/', '/terms/required/', '/logout', '/securetoo/')`

doesn't trigger for actual logout url - `/{language_code}/logout/`

**Comment by cyface** [comment]
Yeah, that setting is literal; so you'd have to put in the language-specific URLs too.  It doesn't use reverse, it just matches exactly.  I'll look at what it would take to enhance to to reverse, and what affect that has on performance.

**Comment by cyface** [comment]
Reversing the urls is too slow; I added a TERMS_EXCLUDE_URL_CONTAINS_LIST to the master branch if you want to try and see if putting /logout/ in there instead of in TERMS_EXCLUDE_URL_LIST makes it work for you.  Cheers!
