### ISSUE TITLE
Changes proposal

### ISSUE THREAD

**Issue by adibo** [cyface/django-termsandconditions#4]
Hi there!

I found your module quite interesting and relevant for our needs. However, for our use case, I would propose a couple of updates/changes:
1. extending the model to include also additional info field, which would contain the message about the change (e.g. could be used as a summary of what is being changed and why). The point here to help users to digest the new terms. 
2. adding a template tag which would allow to display a modal with new terms, if such exists. This can be yet another means to communicate the new terms for users (e.g. by including the tag in the base template), an alternative to redirecting
3. as and extra-add on, to allow for multi-language support (at least for the info) field

If you accept the proposal, I could work towards a respective pull request. Alternatively, if you don't approve, I'm okey with introducing these changes in a separate repo. Let me know.
In any case, thanks a lot for your work and efforts! ;)

Regards,
Adrian

**Comment by cyface** [comment]
Those changes sound good to me! Go for it!



Tim

**Comment by adibo** [comment]
Okey. The pull request is on its way. Please review and (hopefully) accept.
Would be great if you could also release 0.1.6 version on pip upon accepting my PL.

Adrian

**Comment by cyface** [comment]
Changes merged!
