### ISSUE TITLE
Enable handling ToS text fields as template

### ISSUE THREAD

**Issue by adibo** [cyface/django-termsandconditions#40]
Hi,
I came across a use case, where a ToS text has to include other variables and e.g. urls defined by `{% url 'my-url-name' %}`. In general, the ToS text (or other field) could contain template-like syntax.

This could be done by including a `terms.text` in a form of a Template object and using the `include` tag. Thus, one would need to customize the respective template file and use there `{% include terms.text|as_template %}` instead of `{{ terms.text|safe }}`.
I can do a PR with an additional template tag, and help info. Let me know if you think this makes sense.

**Comment by cyface** [comment]
Hi!
 As long as, by default, it works as simple text, I think that is fine. Cheers!

Tim

**Comment by adibo** [comment]
Sure! Simple text is the default. 
PR on its way!
