### ISSUE TITLE
django 1.8 support?

### ISSUE THREAD

**Issue by bcail** [cyface/django-termsandconditions#8]
Thanks for this package - we've been using a fork of it.

I just installed django-termsandconditions from PyPI, and it upgraded my django 1.8 to 1.9. Looks like that's required in setup.py. Is it intentional to not support 1.8 LTS?

**Comment by tlwhit2** [comment]
Yes, unfortunately the amount of changes that I had to do to support 1.9 were extensive, and so I wasn't able to easily support both...that said, the vast majority of the changes in the latest releases have been for Django 1.9 support, so you are probably fine pinning to an older release...

**Comment by bcail** [comment]
OK, thanks. I installed 0.1.7, and that seemed to do the trick.

If someone were to submit PRs to support 1.8 as well as 1.9, would you be open to those?

**Comment by tlwhit2** [comment]
Definitely!

**Comment by bcail** [comment]
Great. I just ran the tests with django 1.9, and then with django 1.8, and both times they all passed. Here are the commands I used (in a new python 2.7 virtual env):
pip install -r termsandconditions_demo/requirements_dev.txt
coverage run --source=termsandconditions,termsandconditions_demo --rcfile=devscripts/checkers/coveragerc manage.py test

Do you know where the issues were with django 1.8?

**Comment by tlwhit2** [comment]
Well, 1.9 removes the 'patterns' stuff from urls.py...I am surprised that works in 1.8.  Maybe the fact that I cleaned them all up to be ur() objects is enough to get that working. I think the TEMPLATES unified settings probably will work back in 1.8...but I wasn't sure.

I'd be sure to test with app integration with 1.8 though, I don't have a 1.8 app to test with.  You would want to make sure the _demo app works cleanly with 1.8 as well.

**Comment by bcail** [comment]
Sure, I have a 1.8 project (actually, I don't have any 1.9 projects yet), and I can confirm that urlpatterns is a list of url objects in 1.8. The unified TEMPLATES setting also works in 1.8.

I'll try to run the demo app a bit, and make sure it looks OK on 1.8.

I'm working on a PR to add 1.8 testing to .travis.yml.

**Comment by bcail** [comment]
OK, I ran the demo app. After adding a user manually, I was able to login and visit the secure pages. I went to the termsrequired/ page, and it made me accept terms before seeing the page. Printing the terms also looked good.

The only issue was the mention of a profile page - I didn't see a button to edit my profile, and at one point I got a redirect to accounts/profile/ and that didn't work. Is that supposed to be part of this app?

**Comment by bcail** [comment]
I opened the PR for adding django 1.8 tests, and I'll check to see if they pass/run correctly.

**Comment by cyface** [comment]
They look good, I'll update the settings.py!

**Comment by cyface** [comment]
PyPi is up to date with the new version 1.1.3!
