### ISSUE TITLE
License of this package

### ISSUE THREAD

**Issue by mcrot** [cyface/django-termsandconditions#88]
Thanks for this package! I'm interested in using it for a web application for scientists in a particular field and I'm wondering what kind of license you want to choose for your package. Is it already decided?

**Comment by cyface** [comment]
MIT License file added, cheers!

**Comment by mcrot** [comment]
Thanks! I've just seen, that the file `setup.py` has the entry 
```
license='BSD'
```
So in PyPI it still appears as BSD. Sorry, I haven't seen this when I opened this issue.
