### ISSUE TITLE
Optional terms and conditions together with a mandatory one

### ISSUE THREAD

**Issue by mcrot** [cyface/django-termsandconditions#89]
We would like to have two kinds of permissions. The first should be mandatory for using the site.
I've seen that this should be easily done with this package by using a middleware. 
We would like to have a second kind if terms of conditions, where we ask our user for their permission to use their measurement data for scientific analyses. Agreeing to this second T&C should be optional, so the users should be able to use the site also if they do not give us their permission.

Is this possible out of the box?

I've seen that when using the middleware, all "active" T&Cs must be confirmed for using the site.
If we created this second T&C as "not active", would it be possible to ask users on first login whether they agree to it or not?

**Comment by cyface** [comment]
Hello! The way it works out of the box is that all active terms are required, and that inactive terms are not shown, typically because they get supplanted with new versions.

You could certainly extend the model to add a field for “optional” terms. But the core purpose of this module is for “required” terms.

Cheers!

**Comment by mcrot** [comment]
Hi @cyface , thanks for your work. In order to have optional terms, I've forked your
project and added optional terms. I've tried to keep the code as close as possible to your code.
The branch can be found [here](https://github.com/mcrot/django-termsandconditions/tree/optional_terms). 

You've already said, that the core purpose of your package is for required terms and conditions.
If you are nevertheless interested, I could open a PR with my additions, just tell me. If not, I understand.

**Comment by mcrot** [comment]
One more comment, this is how I did it:

The entries in the model "UserTermsAndConditions" have now a
different meaning. If a row exists, this means "the terms have been
presented to the user and he/she decided to accept or not to accept"
or in short "terms have been seen by the user".

If the field "date_accepted" is not NULL, the terms have been
accepted. If it is NULL, the user decided not to accept it.

The latter is only possible for "optional terms", these are instances of the
model "TermsAndConditions" having "boolean=True" (new field).
