### ISSUE TITLE
Not saving Remote IP Addres

### ISSUE THREAD

**Issue by wbustamante** [cyface/django-termsandconditions#91]
https://github.com/cyface/django-termsandconditions/blob/9b843faf98909e4eb403981068545c0840b30fed/termsandconditions/views.py#L117

Can you change this line

ip_address = request.META.get(‘HTTP_X_FORWARDED_FOR’, ”) or request.META.get(‘REMOTE_ADDR’) 

because when you are using nginx, REMOTE_ADDR is not present

**Comment by cyface** [comment]
Should be settable as of release 1.2.14.
